package ClassesBeans;
// Generated 16/08/2013 19:11:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPagamento generated by hbm2java
 */
public class FormaPagamento  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private Set vendas = new HashSet(0);

    public FormaPagamento() {
    }

    public FormaPagamento(String descricao, Set vendas) {
       this.descricao = descricao;
       this.vendas = vendas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


