package ClassesBeans;
// Generated 16/08/2013 19:11:44 by Hibernate Tools 3.2.1.GA



/**
 * ItemVenda generated by hbm2java
 */
public class ItemVenda  implements java.io.Serializable {


     private Integer id;
     private Venda venda;
     private Produto produto;
     private Integer quantidade;

    public ItemVenda() {
    }

    public ItemVenda(Venda venda, Produto produto, Integer quantidade) {
       this.venda = venda;
       this.produto = produto;
       this.quantidade = quantidade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }




}


