package ClassesBeans;
// Generated 16/08/2013 19:11:44 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private BigDecimal precoUnitario;
     private String unidade;
     private Integer estoque;
     private Set itemVendas = new HashSet(0);

    public Produto() {
    }

    public Produto(String descricao, BigDecimal precoUnitario, String unidade, Integer estoque, Set itemVendas) {
       this.descricao = descricao;
       this.precoUnitario = precoUnitario;
       this.unidade = unidade;
       this.estoque = estoque;
       this.itemVendas = itemVendas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getPrecoUnitario() {
        return this.precoUnitario;
    }
    
    public void setPrecoUnitario(BigDecimal precoUnitario) {
        this.precoUnitario = precoUnitario;
    }
    public String getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(String unidade) {
        this.unidade = unidade;
    }
    public Integer getEstoque() {
        return this.estoque;
    }
    
    public void setEstoque(Integer estoque) {
        this.estoque = estoque;
    }
    public Set getItemVendas() {
        return this.itemVendas;
    }
    
    public void setItemVendas(Set itemVendas) {
        this.itemVendas = itemVendas;
    }




}


