package ClassesBeans;
// Generated 16/08/2013 19:11:44 by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private FormaPagamento formaPagamento;
     private Integer valorVenda;
     private Integer numeroCartao;
     private Set itemVendas = new HashSet(0);

    public Venda() {
    }

    public Venda(Cliente cliente, FormaPagamento formaPagamento, Integer valorVenda, Integer numeroCartao, Set itemVendas) {
       this.cliente = cliente;
       this.formaPagamento = formaPagamento;
       this.valorVenda = valorVenda;
       this.numeroCartao = numeroCartao;
       this.itemVendas = itemVendas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public FormaPagamento getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(FormaPagamento formaPagamento) {
        this.formaPagamento = formaPagamento;
    }
    public Integer getValorVenda() {
        return this.valorVenda;
    }
    
    public void setValorVenda(Integer valorVenda) {
        this.valorVenda = valorVenda;
    }
    public Integer getNumeroCartao() {
        return this.numeroCartao;
    }
    
    public void setNumeroCartao(Integer numeroCartao) {
        this.numeroCartao = numeroCartao;
    }
    public Set getItemVendas() {
        return this.itemVendas;
    }
    
    public ArrayList getItemVendasAux() {
        return new ArrayList<ItemVenda>(this.itemVendas);
    }
    
    public void setItemVendas(Set itemVendas) {
        this.itemVendas = itemVendas;
    }




}


